### ISSUE TITLE
Failed to sign transaction by a quorum of validators because one or more of its objects is equivocated until the next epoch.  Other transactions locking these objects

### ISSUE THREAD

**Issue by lanxinr** [suidouble/sui_meta#6]
```
JE: Failed to sign transaction by a quorum of validators because one or more of its objects is equivocated until the next epoch.  Other transactions locking these objects:
- 5fCJNr4dzkkECJMdfj6QE1cVMRH8AKghRMtrKhFgWV84 (stake 34.3)
- CWBrUJAeJESp8myakBoY8nRTnobGBUcmsf2KDhkYFco5 (stake 33.42)
    at QD.request (https://suimine.xyz/assets/index-23346564.js:324:14459)
    at async ky.executeTransactionBlock (https://suimine.xyz/assets/index-23346564.js:328:4510)
    at async Ex (https://suimine.xyz/assets/index-23346564.js:2537:1025)
    at async hoe (https://suimine.xyz/assets/index-23346564.js:2537:4223)
    at async boe (https://suimine.xyz/assets/index-23346564.js:2537:6385)
    at async onClick (https://suimine.xyz/assets/index-23346564.js:2537:7372)
```

**Comment by bluesxu** [comment]
same error

**Comment by xy0214** [comment]
Me too

Failed to sign transaction by a quorum of validators because one or more of its objects is equivocated until the next epoch.   Other transactions locking these objects:
- 82MdBeGg7tXrVAAAy2g2dWrfQde38rsovmJ6mt8o8hLj (stake 36.63)
- GKywc2gTg3ctNj8cd5HvVbUT5asoBeCaepUUBdpDufhq (stake 35.2)
at QD. request (index-37beff2f.js:324:14459)
at async ky. executeTransactionBlock (index-37beff2f.js:328:4510)
at async Ex (index-37beff2f.js:2537:1025)
at async hoe (index-37beff2f.js:2537:4223)
at async boe (index-37beff2f.js:2537:6385)
at async onClick (index-37beff2f.js:2537:7372)

**Comment by mddarmawan** [comment]
> Me too
> 
> Failed to sign transaction by a quorum of validators because one or more of its objects is equivocated until the next epoch. Other transactions locking these objects:
> 
> * 82MdBeGg7tXrVAAAy2g2dWrfQde38rsovmJ6mt8o8hLj (stake 36.63)
> * GKywc2gTg3ctNj8cd5HvVbUT5asoBeCaepUUBdpDufhq (stake 35.2)
>   at QD. request (index-37beff2f.js:324:14459)
>   at async ky. executeTransactionBlock (index-37beff2f.js:328:4510)
>   at async Ex (index-37beff2f.js:2537:1025)
>   at async hoe (index-37beff2f.js:2537:4223)
>   at async boe (index-37beff2f.js:2537:6385)
>   at async onClick (index-37beff2f.js:2537:7372)

Just wait for the next epoch, can see it here https://suivision.xyz/. In the meanwhile can use another wallet first
